spring.application.name=online-coaching-system
spring.datasource.url=jdbc:mysql://localhost:3306/onlinecoaching_db
spring.datasource.username=root
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080
spring.web.resources.static-locations=file:uploads/

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
logging.level.org.springframework.security=DEBUG